(setf family
      '((colin nil nil)
        (deirdre nil nil)
        (arthur nil nil)
        (kate nil nil)
        (frank nil nil)
        (linda nil nil)
        (suzanne colin deirdre)
        (bruce arthur kate)
        (charles arthur kate)
        (david arthur kate)
        (ellen arthur kate)
        (george frank linda)
        (hillary frank linda)
        (andre nil nil)
        (tamara bruce suzanne)
        (vincent bruce suzanne)
        (wanda nil nil)
        (ivan george ellen)
        (julie george ellen)
        (marie george ellen)
        (nigel andre hillary)
        (frederick nil tamara)
        (zelda vincent wanda)
        (joshua ivan wanda)
        (quentin nil nil)
        (robert quentin julie)
        (olivia nigel marie)
        (peter nigel marie)
        (erica nil nil)
        (yvette robert zelda)
        (diane peter erica)))

(defun parents (x)
 (remove-if #'null (rest (assoc x family))))

(defun father (x)
 (second (assoc x family)))

(defun mother (x)
  (third (assoc x family)))

(defun children (x)
  (remove-if #'null (mapcar #'(lambda (entry)
                                (if (or (equal x (second entry))
                                        (equal x (third entry)))
                                  (first entry))) family)))

(defun siblings (x)
  (set-difference (union (children (mother x)) (children (father x))) (list x)))

(defun mapunion (func l)
 (and l (reduce #'union (mapcar func l))))

(defun grandparents (x)
 (mapunion #'parents (parents x)))

(defun cousins (x)
 (mapunion #'children (mapunion #'siblings (parents x))))

(defun descended-from (x y)
  (cond ((null x) nil)
        ((member y (parents x)) t)
        (t (or (descended-from (father x) y)
               (descended-from (mother x) y)))))

(defun ancestors (x)
  (cond ((null x) nil)
        (t (union (parents x)
                   (union (ancestors (father x))
                          (ancestors (mother x)))))))

(defun generation-gap-recursive (depth x y)
 (cond ((null x) nil)
       ((equal x y) depth)
       (t (or (generation-gap-recursive (+ 1 depth) (father x) y)
              (generation-gap-recursive (+ 1 depth) (mother x) y)))))

(defun generation-gap (x y)
 (cond ((not (member y (ancestors x))) nil)
       (t (generation-gap-recursive 0 x y))))
